brew-update-local: better logging

diff --git a/cmd/brew-update-local b/cmd/brew-update-local
--- a/cmd/brew-update-local
+++ b/cmd/brew-update-local
@@ -16,6 +16,9 @@ cd "$(dirname "$repo")" || fatal "Unable to cd to $(dirname "$repo")"
 base=${repo##*/}
 real=.real/homebrew-core
 err_log=/tmp/"$(basename "$0")".log
+fail_log=/tmp/"$(basename "$0")".fail
+updated_log=/tmp/"$(basename "$0")".updated
+rm -f "$fail_log" "$updated_log"
 
 info "START: $(basename "$0")"
 
@@ -59,7 +62,7 @@ cmd brew fix-timestamps -C "$real" -f "$repo"/.settings/last_timestamp
 
 info "Updating core repo"
 
-rsync_opts=()
+rsync_opts=(--log-file="$err_log")
 if [[ -s $base/.settings/last_commit ]]; then
   # Let git tell us what changed since the last time we updated
   cmd git -C "$real" log --pretty='format:' --name-only "$(<"$base/.settings/last_commit")"..HEAD | sort -u > "$HOMEBREW_TEMP"/rsync-includes
@@ -88,9 +91,9 @@ cmd rsync -avum "${rsync_opts[@]}" "$real"/ "$base"/
     fbase=$(basename "$f" .rb)
     if cant_build=$(can_build "$f"); then
       # Apply patch if available
-      if [[ -s patches/${fbase}.patch ]] && ! git diff --exit-code "$f" ; then
+      if [[ -s .patches/${fbase}.patch ]] && ! git diff --exit-code "$f" ; then
         info "Patching $f"
-        patch -p1 < patches/"${fbase}".patch
+        patch -p1 < .patches/"${fbase}".patch || echo "${fbase} patch failed" >&3
       fi
       if ! needs_rebottling "$f"; then
         # This formula doesn't need rebuilding
@@ -105,7 +108,7 @@ cmd rsync -avum "${rsync_opts[@]}" "$real"/ "$base"/
       cmd git commit -m "${fbase}: ${cant_build}" "$f"
     fi
   done
-)
+) 3>>"$fail_log"
 
 # Do a Big-Bang fix at the end
 cmd brew style --fix homebrew/core # || fatal "brew style failed"
@@ -136,11 +139,13 @@ cmd brew style --fix homebrew/core # || fatal "brew style failed"
   cmd git pull
   cmd git commit -m "Updates from $real $(date +%Y%m%d.%H%M%S)"
   cmd git push
-)
+) 3>>"$fail_log"
 
 # Record our last commit
 cmd git -C "$real" log --pretty=format:%H HEAD | head -1 | tee "$base/.settings/last_commit"
 
 cmd brew update-core-meta
+
+[[ -s $fail_log ]] && error "Some formulae failed to update. Please check $fail_log for details."
 
 info "DONE: $(basename "$0")"
